
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {{ .Release.Name }}-destination
  namespace: {{.Values.namespace}}
spec: 
  clusterServiceClassExternalName: destination
  clusterServicePlanExternalName: lite

---

apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: {{ .Release.Name }}-xsuaa
  namespace: {{.Values.namespace}}
spec:
  clusterServiceClassExternalName: xsuaa
  clusterServicePlanExternalName: application
  parameters:
    xsappname: {{ .Release.Name }}-BusinessParnterManagement
    tenant-mode: dedicated
    oauth2-configuration:
      redirect-uris:
        - https://*.{{ .Values.clusterurl }}/login/callback

