apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: {{ .Release.Name }}-updfunc-subscription
  namespace: {{.Values.namespace}}
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.nonexistingapp.businesspartner.update.v1
  protocol: ""
  protocolsettings: {}
  sink: http://{{ .Release.Name }}-updfunc.{{.Values.namespace}}.svc.cluster.local