apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: event-emitter
  namespace: advanced
  labels:
    app: event-emitter
    example: event-emitter
spec:
  deps: |-
    {
      "name":"event-emitter",
      "version":"1.0.0",
      "dependencies":{
          "axios":"^0.21.1",
          "cloudevents":"^4.0.3",
          "uuid":"^8.3.2"
      }
    }
  maxReplicas: 1
  minReplicas: 1
  resources:
    limits:
      cpu: 20m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 16Mi
  env:
    - name: EVENT_TYPE
      value: "sap.kyma.custom.nonexistingapp.event.registration.v1"
    - name: EVENT_SOURCE
      value: "/advanced/my.kyma/test"
    - name: PUBLISHER_URL
      value: "http://eventing-event-publisher-proxy.kyma-system/publish"

  source: |-
    const axios = require("axios").default;
    const { HTTP, CloudEvent } = require("cloudevents");
    const { v4: uuidv4 } = require('uuid');

    module.exports = { 
      main: async function (event, context) {

        console.log('event.data: ', event.data);

        const ce = new CloudEvent({
          id: event.id,
          type: process.env.EVENT_TYPE,
          source: process.env.EVENT_SOURCE,
          data: event.data,
          datacontenttype: "application/json"
        });

        const message = HTTP.structured(ce);

        axios({
          method: "post",
          url: process.env.PUBLISHER_URL,
          data: message.body,
          headers: message.headers
        });

        res = event.extensions.response;
        res.status(200);
        return { message: "success", uuid: uuidv4() };
      }
    }